## Notebook for looking at the Government.csv

In [48]:
import pandas as pd

In [49]:
df = pd.read_csv('../../Notebooks/Datasets/Economic_dataset/Government.csv')
for col in df.columns:
    print(col)
df

Date Time
Unnamed: 1
Unnamed: 2
Unnamed: 3
Event

,Date Time,Unnamed: 1,Unnamed: 2,Unnamed: 3,Event
0,01/02/2000 10:00,UK,1),NaN,Prime Minister's Question Time
1,01/10/2000 09:30,UK,2),NaN,Social Security Secretary Answers Questions in...
2,01/10/2000,UK,3),NaN,Houses of Parliament Resume Sitting
3,01/11/2000 09:30,UK,4),NaN,Transport Secretary Answers Questions in Parli...
4,01/12/2000 10:00,UK,5),NaN,Prime Minister's Question Time
...,...,...,...,...,...
4123,10/03/2021 10/06,UK,4124),NaN,Conservative Party Conference in Manchester
4124,10/27/2021 07:30,UK,4125),NaN,U.K. Budget
4125,11/01/2021 07:00,UK,4126),NaN,U.K. OBR chiefs testify
4126,11/01/2021 11:15,UK,4127),NaN,U.K. Chancellor of the Exchequer Rishi Sunak t...
4127,11/02/2021 11:00,UK,4128),NaN,U.K.'s Sunak testifies on budget

 Drop Irrelavant Fields

In [50]:
df2 = df.drop(columns=["Unnamed: 1","Unnamed: 2","Unnamed: 3"])
df2

             Date Time                                              Event
0     01/02/2000 10:00                     Prime Minister's Question Time
1     01/10/2000 09:30  Social Security Secretary Answers Questions in...
2           01/10/2000                Houses of Parliament Resume Sitting
3     01/11/2000 09:30  Transport Secretary Answers Questions in Parli...
4     01/12/2000 10:00                     Prime Minister's Question Time
...                ...                                                ...
4123  10/03/2021 10/06        Conservative Party Conference in Manchester
4124  10/27/2021 07:30                                        U.K. Budget
4125  11/01/2021 07:00                            U.K. OBR chiefs testify
4126  11/01/2021 11:15  U.K. Chancellor of the Exchequer Rishi Sunak t...
4127  11/02/2021 11:00                   U.K.'s Sunak testifies on budget

[4128 rows x 2 columns]

Type of Events

In [52]:
Events = df2.drop(columns = ["Date Time"]).drop_duplicates("Event")
Events

                                                  Event
0                        Prime Minister's Question Time
1     Social Security Secretary Answers Questions in...
2                   Houses of Parliament Resume Sitting
3     Transport Secretary Answers Questions in Parli...
5     Agriculture Secretary Answers Questions in Par...
...                                                 ...
4121   Group of Seven finance ministers conference call
4123        Conservative Party Conference in Manchester
4125                            U.K. OBR chiefs testify
4126  U.K. Chancellor of the Exchequer Rishi Sunak t...
4127                   U.K.'s Sunak testifies on budget

[2874 rows x 1 columns]

Filter By Events

In [58]:
event = "Prime Minister's Question Time" #Type of event
filtered_by_event = df2[df2["Event"] == event]
filtered_by_event

            Date Time                           Event
0    01/02/2000 10:00  Prime Minister's Question Time
4    01/12/2000 10:00  Prime Minister's Question Time
11   01/19/2000 10:00  Prime Minister's Question Time
15   01/26/2000 10:00  Prime Minister's Question Time
20   02/02/2000 10:00  Prime Minister's Question Time
24   02/09/2000 10:00  Prime Minister's Question Time
28   02/16/2000 10:00  Prime Minister's Question Time
34   03/01/2000 10:00  Prime Minister's Question Time
38   03/08/2000 10:00  Prime Minister's Question Time
42   03/15/2000 10:00  Prime Minister's Question Time
46   03/22/2000 10:00  Prime Minister's Question Time
49   03/29/2000 11:00  Prime Minister's Question Time
59   04/05/2000 10:00  Prime Minister's Question Time
64   04/12/2000 10:00  Prime Minister's Question Time
70   04/19/2000 10:00  Prime Minister's Question Time
74   05/03/2000 10:00  Prime Minister's Question Time
79   05/10/2000 10:00  Prime Minister's Question Time
85   05/17/2000 10:00  Prime Minister's Question Time
90   05/24/2000 10:00  Prime Minister's Question Time
100  06/14/2000 10:00  Prime Minister's Question Time
109  06/21/2000 10:00  Prime Minister's Question Time
116  06/28/2000 10:00  Prime Minister's Question Time
124  07/05/2000 10:00  Prime Minister's Question Time
132  07/12/2000 10:00  Prime Minister's Question Time
139  07/19/2000 10:00  Prime Minister's Question Time
145  07/26/2000 10:00  Prime Minister's Question Time
156  10/25/2000 10:00  Prime Minister's Question Time
162  11/01/2000 10:00  Prime Minister's Question Time
172  11/08/2000 10:00  Prime Minister's Question Time
180  11/15/2000 10:00  Prime Minister's Question Time
191  11/22/2000 10:00  Prime Minister's Question Time
200  11/29/2000 10:00  Prime Minister's Question Time
219  02/07/2001 10:00  Prime Minister's Question Time
223  02/14/2001 10:00  Prime Minister's Question Time
229  02/28/2001 10:00  Prime Minister's Question Time
231  03/07/2001 10:00  Prime Minister's Question Time
238  03/14/2001 10:00  Prime Minister's Question Time
244  03/21/2001 10:00  Prime Minister's Question Time
250  03/28/2001 09:00  Prime Minister's Question Time
255  04/04/2001 10:00  Prime Minister's Question Time
272  06/27/2001 10:00  Prime Minister's Question Time
273  07/04/2001 10:00  Prime Minister's Question Time
301  10/17/2001 10:00  Prime Minister's Question Time
306  10/24/2001 10:00  Prime Minister's Question Time
309  10/31/2001 10:00  Prime Minister's Question Time
313  11/07/2001 10:00  Prime Minister's Question Time
316  11/14/2001 10:00  Prime Minister's Question Time
322  11/21/2001 10:00  Prime Minister's Question Time
331  12/05/2001 10:00  Prime Minister's Question Time
334  12/12/2001 10:00  Prime Minister's Question Time
338  12/19/2001 10:00  Prime Minister's Question Time

Filter By Date

In [69]:
Day = 20
Month = 11
Year = 2001

Date = str(Month)+"/"+str(Day)+"/"+str(Year) #Type of event
filtered_by_date = df2[df2["Date Time"].str.contains(Date)]
filtered_by_date

            Date Time                                              Event
320  11/20/2001 04:30                             Budget Deficit Figures
321  11/20/2001 09:30  Transport, Local Government, Regions Questions...